[package]
name = "encrypto-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
encrypto-core = { path = "../encrypto-core" }
encrypto-pgp = { path = "../encrypto-pgp" }
