[package]
name = "encrypto-pgp"
version = "0.1.0"
edition = "2024"

[dependencies]
encrypto-core = { path = "../encrypto-core" }
tempfile = "3"
dirs = "5"
sequoia-openpgp = { version = "2.2.0-pqc.1", default-features = false, features = ["crypto-openssl"] }
